# Generated by Django 3.0.7 on 2020-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reductcontract', '0005_auto_20200611_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['finish_date']},
        ),
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
