# Generated by Django 3.0.7 on 2020-06-18 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reductcontract', '0008_contractor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='clause',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='on_board',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
    ]
