# Generated by Django 3.0.7 on 2020-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reductcontract', '0009_auto_20200618_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='on_board',
            field=models.DateField(default=models.DateField()),
        ),
    ]
