# Generated by Django 2.2.5 on 2020-06-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reductcontract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='myprofile.png', upload_to='images/'),
        ),
    ]
