# Generated by Django 3.0.7 on 2020-06-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reductcontract', '0006_auto_20200617_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='status',
        ),
    ]
