# This is a basic workflow to help you get started with Actions

name: CD PROD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the latest code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create .env file
        run: |
          touch .env
          cat > .env << EOL
          POSTGRES_USER=${{ secrets.PROD__POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.PROD__POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.PROD__POSTGRES_DB }}
          DATABASE=${{ secrets.PROD__DATABASE }}
          DATABASE_HOST=${{ secrets.PROD__DATABASE_HOST }}
          DATABASE_PORT=${{ secrets. PROD__DATABASE_PORT }}
          SECRET_KEY=${{ secrets.PROD__SECRET_KEY }}
          SENDGRID_API_KEY=${{ secrets.PROD__SENDGRID_API_KEY }}
          EOL

      - name: Deploy to Production server
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H 159.65.154.191 >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.PROD__SSH_PRIVATE_KEY }}"
          chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ root@159.65.154.191:/root/contract-mgmt
